[package]
name = "sync"
version = "0.1.1"
edition = "2021"

[profile.release]
strip = true

[dependencies]
atty = "0.2.14"
crossterm = "0.25.0"
eframe = "0.20.1"
execute = "0.2.11"
open = "3.2.0"
toml = "0.5.10"
