[package]
name = "sync"
version = "1.4.1"
edition = "2021"

[profile.release]
strip = true

[dependencies]
atty = "0.2.14"
crossterm = "0.25.0"
eframe = "0.20.1"
execute = "0.2.11"
git2 = "0.16.1"
opener = "0.5.0"
serde = { version = "1.0.152", features = ["derive"] }
toml = "0.5.10"
