[package]
name = "sync"
version = "0.1.1"
edition = "2021"

[profile.release]
strip = true
opt-level = "s"
lto = true

[dependencies]
atty = "0.2.14"
crossterm = "0.25.0"
execute = "0.2.11"
toml = "0.5.10"
