// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export interface Folder {
  branch: string | null;
  repo: string | null;
  run_instancesync: boolean;
  server: boolean;
  sync: boolean;
  name: string;
  path: string | null;
  path_shortname: string | null;
}
